### ISSUE TITLE
Needs to be updated for current use

### ISSUE THREAD

**Issue by Silvus10** [RedBrumbler/BMBFCustomSabers#5]
[MasterSabers.zip](https://github.com/RedBrumbler/BMBFCustomSabers/files/3894431/MasterSabers.zip)

Hey, sorry to be a bother but i am a huge LOZ fan (I've even got the Triforce of courage on the back of my right hand, painful wouldn't recommend)  and love this saber mod, but it appears to currently be unusable when loaded onto the quest. For some reason, I can add the mod but can't activate it. I have a basic understanding of file management but explain like I'm a child (I'm not, but i'm easily confused), I'm still learning. Any help would be greatly appreciated :D

**Comment by RedBrumbler** [comment]
I would like to refer you to my saber guide at the top, there it says the sharedassets mutations you need to apply

Just open the zip and go into the bmbfmod.json and change the sharedassets files to the ones defined in my saber guide, that should help you!

**Comment by Silvus10** [comment]
> I would like to refer you to my saber guide at the top, there it says the sharedassets mutations you need to apply
> 
> Just open the zip and go into the bmbfmod.json and change the sharedassets files to the ones defined in my saber guide, that should help you!

Hey, so I went ahead and performed the steps (which I think was changing the sharedassets number from 14-15) and now the mod registers as successfully installed and activated, but when I go to the activation tick, it doesnt stay, and instead gives me a short burst of "failed: ReplaceAssetOp" that all read "unable to read beyond the end of stream",  have I done something wrong?

Edit/update: occasionally, I get the same Failed: ReplaceAssetOp, but the error states "The locator throw an exception, possibly because it returned more than one matching asset"

**Comment by RedBrumbler** [comment]
Oh wait this is the one that has an edited transform... that makes it harder because idk how to fix that exactly seeing as I never edit the transform, I think pinksaber on discord made a master sword too, try finding that one and updating it, seeing as that one does not use an edited transform
